/**
 * ThermoSentinel AI - Inspection Reports & Work Order Generator
 */

export class ReportGenerator {
  static generateWorkOrderHTML(asset) {
    if (!asset) return '';
    const deltaT = (asset.currentScanTemp - asset.referenceTemp).toFixed(1);
    const dateStr = new Date().toISOString().replace('T', ' ').substring(0, 19);

    return `
      <div class="work-order-document">
        <div class="wo-header">
          <div class="wo-brand">
            <span class="wo-logo">🚁 THERMOSENTINEL AI</span>
            <span class="wo-sub">AUTONOMOUS INDUSTRIAL SAFETY PLATFORM</span>
          </div>
          <div class="wo-meta">
            <div><strong>WORK ORDER #:</strong> WO-2026-${asset.id}-09</div>
            <div><strong>INSPECTION DATE:</strong> ${asset.lastScanDate || dateStr}</div>
            <div><strong>FACILITY ZONE:</strong> ${asset.zone}</div>
          </div>
        </div>

        <div class="wo-alert-banner alert-${asset.status}">
          <div class="wo-status-title">SEVERITY LEVEL: ${asset.status.toUpperCase()}</div>
          <div>EQUIPMENT TARGET: ${asset.id} - ${asset.name}</div>
        </div>

        <div class="wo-grid">
          <div class="wo-section">
            <h4>THERMAL MEASUREMENT METRICS</h4>
            <table class="wo-table">
              <tr><td>Reference Baseline Temp:</td><td><strong>${asset.referenceTemp} °C</strong></td></tr>
              <tr><td>Current Scan Max Temp:</td><td><strong class="text-${asset.status}">${asset.currentScanTemp} °C</strong></td></tr>
              <tr><td>Delta T (ΔT Anomaly):</td><td><strong class="text-${asset.status}">+${deltaT} °C</strong></td></tr>
              <tr><td>Ambient Temperature:</td><td>${asset.ambientTemp} °C</td></tr>
              <tr><td>Operating Load:</td><td>${asset.loadPercentage}% (${asset.actualCurrent}A / ${asset.ratedCurrent}A)</td></tr>
              <tr><td>Specific Hotspot Location:</td><td>${asset.hotspotTarget}</td></tr>
            </table>
          </div>

          <div class="wo-section">
            <h4>AI DIAGNOSTIC ROOT-CAUSE ANALYSIS</h4>
            <div class="wo-text-box">
              ${asset.diagnosis}
            </div>
          </div>
        </div>

        <div class="wo-section mt-4">
          <h4>RECOMMENDED CORRECTIVE ACTION & SAFETY PROTOCOL</h4>
          <div class="wo-action-box">
            ${asset.recommendedAction}
          </div>
        </div>

        <div class="wo-signatures">
          <div class="sig-box">
            <div class="sig-line"></div>
            <div>AI Inspector Specialist Sign-off</div>
          </div>
          <div class="sig-box">
            <div class="sig-line"></div>
            <div>Plant Electrical Safety Chief Approval</div>
          </div>
        </div>

        <div class="wo-footer">
          <div>Generated by ThermoSentinel AI Mission Control | Standards: NETA MTS-2023 / IEEE C57.12.00</div>
        </div>
      </div>
    `;
  }
}

window.ReportGenerator = ReportGenerator;
